version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

jobs:
  build:
    working_directory: ~/DevOpsSec-Group-Project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@5'  
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install-npm
          command: npm install
      - run:
          name: test-npm
          command: npm run test || true
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS 
           rm -rf DevOpsSec-Group-Project/; 
           git clone https://github.com/Hope52411/DevOpsSec-Group-Project.git; 
           source DevOpsSec-Group-Project/deploy.sh"